version: '3'

services:
#  server:
#    build: ./app/server
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./app/server:/main
#  client:
#    build: ./app/client
#    ports:
#      - "8081:8080"
#    volumes:
#      - ./app/client:/main
  db:
    image: postgres:14
    restart: always
    container_name: user-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "2346:5432"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - /path/to/local/directory:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3