version: '3'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    container_name: user-service
##    command: bash -c "yoyo init --database postgresql+psycopg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME} migrations && yoyo develop && python -m app"
#
#    command: bash -c "yoyo develop && python -m app"
#    ports:
#      - "50052:50052"
#    depends_on:
#      - db
#      - minio

  db:
    image: postgres:14
    restart: always
    container_name: user-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "2346:5432"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    volumes:
      - /path/to/local/directory:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3